### ISSUE TITLE
Search input broken; console error on every keypress

### ISSUE THREAD

**Issue by HasanAbbadi** [Wamy-Dev/ReziWebsite#15]
Hey,
I've noticed today that the input is not working, anything I press is not displayed nor searched for.
So I took a look in the console and on every keypress there seems to be a console error that says:
```
Uncaught TypeError: el is not a function
    at onChange (main.941436dd.js:1:546422)
    at onChange (main.941436dd.js:1:485728)
    at Object.Ne (main.941436dd.js:1:203008)
    at He (main.941436dd.js:1:203162)
    at main.941436dd.js:1:223062
    at Br (main.941436dd.js:1:223156)
    at Dr (main.941436dd.js:1:223571)
    at main.941436dd.js:1:229013
    at cc (main.941436dd.js:1:292682)
    at je (main.941436dd.js:1:202140)
```

Hope you can get this fixed soon.
And thanks for the great tool.

**Comment by Wamy-Dev** [comment]
Sorry about that. I added analytics to the search bar and I guess SimpleAnalytics event code doesn't work well. This should be fixed now.
